// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const SystemRole = {
    /**
     * Regular member of the system.
     */
    User: "system_user",
    /**
     * System administrator with full access to the System Console.
     */
    Admin: "system_admin",
    /**
     * Guest account restricted to the channels it is added to.
     */
    Guest: "system_guest",
    /**
     * System manager with access to most System Console sections.
     */
    Manager: "system_manager",
    /**
     * User manager who can manage users, teams and channels.
     */
    UserManager: "system_user_manager",
    /**
     * Read-only access to the System Console.
     */
    ReadOnlyAdmin: "system_read_only_admin",
    /**
     * Can manage custom user groups.
     */
    CustomGroupAdmin: "system_custom_group_admin",
    /**
     * Can post to any channel, including private channels and direct messages.
     */
    PostAll: "system_post_all",
    /**
     * Can post to any public channel.
     */
    PostAllPublic: "system_post_all_public",
    /**
     * Can create personal access tokens.
     */
    UserAccessToken: "system_user_access_token",
} as const;

export type SystemRole = (typeof SystemRole)[keyof typeof SystemRole];
