// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("mattermost");

/**
 * Base URL of the Mattermost instance, e.g. https://mattermost.example.com. Defaults to MATTERMOST_BASE_URL.
 */
export declare const baseUrl: string;
Object.defineProperty(exports, "baseUrl", {
    get() {
        return __config.get("baseUrl") ?? (utilities.getEnv("MATTERMOST_BASE_URL") || "");
    },
    enumerable: true,
});

/**
 * Mattermost personal access token or bot token. Defaults to MATTERMOST_TOKEN. May be omitted for a provider that only creates a Bootstrap resource.
 */
export declare const token: string;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token") ?? (utilities.getEnv("MATTERMOST_TOKEN") || "");
    },
    enumerable: true,
});

