// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * The configuration of the Agents plugin (mattermost-ai): its LLM services and plugin-wide switches, written to the plugin's admin configuration endpoint. The plugin must be installed and enabled, for example through a Plugin resource, and the provider's account must be a system admin. `services` replaces the plugin's service list; unset switches and everything else the endpoint holds (MCP servers, web search, embedding search, legacy bots) are left as they are. This is a singleton resource with ID `mattermost-ai`. Deleting the resource stops managing the configuration and keeps it on the server, because agents keep referring to the services.
 */
export class AgentsConfig extends pulumi.CustomResource {
    /**
     * Get an existing AgentsConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): AgentsConfig {
        return new AgentsConfig(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:AgentsConfig';

    /**
     * Returns true if the given object is an instance of AgentsConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AgentsConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AgentsConfig.__pulumiType;
    }

    /**
     * Allow the LLM's native web search in channels.
     */
    declare public readonly allowNativeWebSearchInChannels: pulumi.Output<boolean | undefined>;
    /**
     * Allow links to non-HTTPS or private hosts in agent output.
     */
    declare public readonly allowUnsafeLinks: pulumi.Output<boolean | undefined>;
    /**
     * Comma-separated hostnames the agents may fetch, for example for link previews and tools.
     */
    declare public readonly allowedUpstreamHostnames: pulumi.Output<string | undefined>;
    /**
     * Offer summaries of Calls recordings.
     */
    declare public readonly enableCallSummary: pulumi.Output<boolean | undefined>;
    /**
     * Let agents call tools when mentioned in a channel.
     */
    declare public readonly enableChannelMentionToolCalling: pulumi.Output<boolean | undefined>;
    /**
     * Log token usage.
     */
    declare public readonly enableTokenUsageLogging: pulumi.Output<boolean | undefined>;
    /**
     * The LLM services, replacing the plugin's list. Agents refer to a service by its `id`.
     */
    declare public readonly services: pulumi.Output<outputs.AgentsService[]>;
    /**
     * ID of the service that transcribes Calls recordings.
     */
    declare public readonly transcriptBackend: pulumi.Output<string | undefined>;

    /**
     * Create a AgentsConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AgentsConfigArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.services === undefined && !opts.urn) {
                throw new Error("Missing required property 'services'");
            }
            resourceInputs["allowNativeWebSearchInChannels"] = args?.allowNativeWebSearchInChannels;
            resourceInputs["allowUnsafeLinks"] = args?.allowUnsafeLinks;
            resourceInputs["allowedUpstreamHostnames"] = args?.allowedUpstreamHostnames;
            resourceInputs["enableCallSummary"] = args?.enableCallSummary;
            resourceInputs["enableChannelMentionToolCalling"] = args?.enableChannelMentionToolCalling;
            resourceInputs["enableTokenUsageLogging"] = args?.enableTokenUsageLogging;
            resourceInputs["services"] = args?.services;
            resourceInputs["transcriptBackend"] = args?.transcriptBackend;
        } else {
            resourceInputs["allowNativeWebSearchInChannels"] = undefined /*out*/;
            resourceInputs["allowUnsafeLinks"] = undefined /*out*/;
            resourceInputs["allowedUpstreamHostnames"] = undefined /*out*/;
            resourceInputs["enableCallSummary"] = undefined /*out*/;
            resourceInputs["enableChannelMentionToolCalling"] = undefined /*out*/;
            resourceInputs["enableTokenUsageLogging"] = undefined /*out*/;
            resourceInputs["services"] = undefined /*out*/;
            resourceInputs["transcriptBackend"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AgentsConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a AgentsConfig resource.
 */
export interface AgentsConfigArgs {
    /**
     * Allow the LLM's native web search in channels.
     */
    allowNativeWebSearchInChannels?: pulumi.Input<boolean | undefined>;
    /**
     * Allow links to non-HTTPS or private hosts in agent output.
     */
    allowUnsafeLinks?: pulumi.Input<boolean | undefined>;
    /**
     * Comma-separated hostnames the agents may fetch, for example for link previews and tools.
     */
    allowedUpstreamHostnames?: pulumi.Input<string | undefined>;
    /**
     * Offer summaries of Calls recordings.
     */
    enableCallSummary?: pulumi.Input<boolean | undefined>;
    /**
     * Let agents call tools when mentioned in a channel.
     */
    enableChannelMentionToolCalling?: pulumi.Input<boolean | undefined>;
    /**
     * Log token usage.
     */
    enableTokenUsageLogging?: pulumi.Input<boolean | undefined>;
    /**
     * The LLM services, replacing the plugin's list. Agents refer to a service by its `id`.
     */
    services: pulumi.Input<pulumi.Input<inputs.AgentsServiceArgs>[]>;
    /**
     * ID of the service that transcribes Calls recordings.
     */
    transcriptBackend?: pulumi.Input<string | undefined>;
}
