// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A self-service agent of the Agents plugin (mattermost-ai): a bot account backed by one of the plugin's LLM services, created through the plugin's agents endpoint. The plugin must be installed and enabled and the provider's account must be a system admin. Without an E20 or Enterprise license the plugin allows one agent per server. The resource ID is the agent ID; deleting it removes the agent and its bot account.
 */
export class Agent extends pulumi.CustomResource {
    /**
     * Get an existing Agent resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Agent {
        return new Agent(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:Agent';

    /**
     * Returns true if the given object is an instance of Agent.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Agent {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Agent.__pulumiType;
    }

    /**
     * User IDs that may edit the agent besides its creator and system admins.
     */
    declare public readonly adminUserIds: pulumi.Output<string[] | undefined>;
    /**
     * Give the agent every configured MCP tool, including ones added later.
     */
    declare public readonly autoEnableNewMcpTools: pulumi.Output<boolean | undefined>;
    /**
     * User ID of the agent's bot account.
     */
    declare public /*out*/ readonly botUserId: pulumi.Output<string>;
    /**
     * Which channels may use the agent. Defaults to all.
     */
    declare public readonly channelAccessLevel: pulumi.Output<enums.AgentAccessLevel | undefined>;
    /**
     * Channel IDs the channel access level allows or blocks.
     */
    declare public readonly channelIds: pulumi.Output<string[] | undefined>;
    /**
     * System prompt added to every conversation.
     */
    declare public readonly customInstructions: pulumi.Output<string | undefined>;
    /**
     * Disable tool calling.
     */
    declare public readonly disableTools: pulumi.Output<boolean | undefined>;
    /**
     * Display name of the agent.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Let the agent read images.
     */
    declare public readonly enableVision: pulumi.Output<boolean | undefined>;
    /**
     * Names of the plugin's built-in tools the agent may call; none when unset.
     */
    declare public readonly enabledNativeTools: pulumi.Output<string[] | undefined>;
    /**
     * Maximum tool-calling turns per response; 0 lets the plugin choose.
     */
    declare public readonly maxToolTurns: pulumi.Output<number | undefined>;
    /**
     * Let the agent discover and load MCP tools on demand instead of receiving every tool definition up front.
     */
    declare public readonly mcpDynamicToolLoading: pulumi.Output<boolean | undefined>;
    /**
     * Model to use; the service's default model when unset.
     */
    declare public readonly model: pulumi.Output<string | undefined>;
    /**
     * Reasoning effort for models that support it, for example `low`, `medium` or `high`.
     */
    declare public readonly reasoningEffort: pulumi.Output<string | undefined>;
    /**
     * Enable extended reasoning where the model supports it.
     */
    declare public readonly reasoningEnabled: pulumi.Output<boolean | undefined>;
    /**
     * ID of the LLM service the agent uses, see AgentsConfig.
     */
    declare public readonly serviceId: pulumi.Output<string>;
    /**
     * Ask the model for structured output.
     */
    declare public readonly structuredOutputEnabled: pulumi.Output<boolean | undefined>;
    /**
     * Team IDs whose members may talk to the agent.
     */
    declare public readonly teamIds: pulumi.Output<string[] | undefined>;
    /**
     * Thinking token budget for models that support it; 0 lets the plugin choose.
     */
    declare public readonly thinkingBudget: pulumi.Output<number | undefined>;
    /**
     * Which users may talk to the agent. Defaults to all.
     */
    declare public readonly userAccessLevel: pulumi.Output<enums.AgentAccessLevel | undefined>;
    /**
     * User IDs the user access level allows or blocks.
     */
    declare public readonly userIds: pulumi.Output<string[] | undefined>;
    /**
     * Username of the agent's bot account: a lowercase letter followed by lowercase letters, digits, dots, hyphens or underscores. Changing it replaces the agent.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a Agent resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AgentArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["adminUserIds"] = args?.adminUserIds;
            resourceInputs["autoEnableNewMcpTools"] = args?.autoEnableNewMcpTools;
            resourceInputs["channelAccessLevel"] = args?.channelAccessLevel;
            resourceInputs["channelIds"] = args?.channelIds;
            resourceInputs["customInstructions"] = args?.customInstructions;
            resourceInputs["disableTools"] = args?.disableTools;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["enableVision"] = args?.enableVision;
            resourceInputs["enabledNativeTools"] = args?.enabledNativeTools;
            resourceInputs["maxToolTurns"] = args?.maxToolTurns;
            resourceInputs["mcpDynamicToolLoading"] = args?.mcpDynamicToolLoading;
            resourceInputs["model"] = args?.model;
            resourceInputs["reasoningEffort"] = args?.reasoningEffort;
            resourceInputs["reasoningEnabled"] = args?.reasoningEnabled;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["structuredOutputEnabled"] = args?.structuredOutputEnabled;
            resourceInputs["teamIds"] = args?.teamIds;
            resourceInputs["thinkingBudget"] = args?.thinkingBudget;
            resourceInputs["userAccessLevel"] = args?.userAccessLevel;
            resourceInputs["userIds"] = args?.userIds;
            resourceInputs["username"] = args?.username;
            resourceInputs["botUserId"] = undefined /*out*/;
        } else {
            resourceInputs["adminUserIds"] = undefined /*out*/;
            resourceInputs["autoEnableNewMcpTools"] = undefined /*out*/;
            resourceInputs["botUserId"] = undefined /*out*/;
            resourceInputs["channelAccessLevel"] = undefined /*out*/;
            resourceInputs["channelIds"] = undefined /*out*/;
            resourceInputs["customInstructions"] = undefined /*out*/;
            resourceInputs["disableTools"] = undefined /*out*/;
            resourceInputs["displayName"] = undefined /*out*/;
            resourceInputs["enableVision"] = undefined /*out*/;
            resourceInputs["enabledNativeTools"] = undefined /*out*/;
            resourceInputs["maxToolTurns"] = undefined /*out*/;
            resourceInputs["mcpDynamicToolLoading"] = undefined /*out*/;
            resourceInputs["model"] = undefined /*out*/;
            resourceInputs["reasoningEffort"] = undefined /*out*/;
            resourceInputs["reasoningEnabled"] = undefined /*out*/;
            resourceInputs["serviceId"] = undefined /*out*/;
            resourceInputs["structuredOutputEnabled"] = undefined /*out*/;
            resourceInputs["teamIds"] = undefined /*out*/;
            resourceInputs["thinkingBudget"] = undefined /*out*/;
            resourceInputs["userAccessLevel"] = undefined /*out*/;
            resourceInputs["userIds"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["username"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Agent.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Agent resource.
 */
export interface AgentArgs {
    /**
     * User IDs that may edit the agent besides its creator and system admins.
     */
    adminUserIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Give the agent every configured MCP tool, including ones added later.
     */
    autoEnableNewMcpTools?: pulumi.Input<boolean | undefined>;
    /**
     * Which channels may use the agent. Defaults to all.
     */
    channelAccessLevel?: pulumi.Input<enums.AgentAccessLevel | undefined>;
    /**
     * Channel IDs the channel access level allows or blocks.
     */
    channelIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * System prompt added to every conversation.
     */
    customInstructions?: pulumi.Input<string | undefined>;
    /**
     * Disable tool calling.
     */
    disableTools?: pulumi.Input<boolean | undefined>;
    /**
     * Display name of the agent.
     */
    displayName: pulumi.Input<string>;
    /**
     * Let the agent read images.
     */
    enableVision?: pulumi.Input<boolean | undefined>;
    /**
     * Names of the plugin's built-in tools the agent may call; none when unset.
     */
    enabledNativeTools?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Maximum tool-calling turns per response; 0 lets the plugin choose.
     */
    maxToolTurns?: pulumi.Input<number | undefined>;
    /**
     * Let the agent discover and load MCP tools on demand instead of receiving every tool definition up front.
     */
    mcpDynamicToolLoading?: pulumi.Input<boolean | undefined>;
    /**
     * Model to use; the service's default model when unset.
     */
    model?: pulumi.Input<string | undefined>;
    /**
     * Reasoning effort for models that support it, for example `low`, `medium` or `high`.
     */
    reasoningEffort?: pulumi.Input<string | undefined>;
    /**
     * Enable extended reasoning where the model supports it.
     */
    reasoningEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * ID of the LLM service the agent uses, see AgentsConfig.
     */
    serviceId: pulumi.Input<string>;
    /**
     * Ask the model for structured output.
     */
    structuredOutputEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Team IDs whose members may talk to the agent.
     */
    teamIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Thinking token budget for models that support it; 0 lets the plugin choose.
     */
    thinkingBudget?: pulumi.Input<number | undefined>;
    /**
     * Which users may talk to the agent. Defaults to all.
     */
    userAccessLevel?: pulumi.Input<enums.AgentAccessLevel | undefined>;
    /**
     * User IDs the user access level allows or blocks.
     */
    userIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Username of the agent's bot account: a lowercase letter followed by lowercase letters, digits, dots, hyphens or underscores. Changing it replaces the agent.
     */
    username: pulumi.Input<string>;
}
