// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * Obtains a system-admin bot token without user interaction. On a fresh server the admin account is signed up as the first user (which Mattermost promotes to system admin); on a running server the admin credentials or an existing admin token are used. The bot is created or adopted, its system roles applied and an access token issued. The resource authenticates on its own, so its provider does not need a token. The resource ID is the bot's user ID.
 */
export class Bootstrap extends pulumi.CustomResource {
    /**
     * Get an existing Bootstrap resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Bootstrap {
        return new Bootstrap(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:Bootstrap';

    /**
     * Returns true if the given object is an instance of Bootstrap.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bootstrap {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bootstrap.__pulumiType;
    }

    /**
     * Email of the bootstrap admin. Only used when the account is created.
     */
    declare public readonly adminEmail: pulumi.Output<string>;
    /**
     * Password of the bootstrap admin. Required unless adminToken is set.
     */
    declare public readonly adminPassword: pulumi.Output<string | undefined>;
    /**
     * Existing system-admin token (personal access or bot token) used instead of a password login.
     */
    declare public readonly adminToken: pulumi.Output<string | undefined>;
    /**
     * User ID of the bootstrap admin.
     */
    declare public /*out*/ readonly adminUserId: pulumi.Output<string>;
    /**
     * Username of the bootstrap admin. Created on a fresh server, used for login otherwise.
     */
    declare public readonly adminUsername: pulumi.Output<string>;
    /**
     * Base URL of the Mattermost instance. Defaults to the provider's base URL.
     */
    declare public readonly baseUrl: pulumi.Output<string | undefined>;
    /**
     * Description of the bot.
     */
    declare public readonly botDescription: pulumi.Output<string | undefined>;
    /**
     * Display name of the bot.
     */
    declare public readonly botDisplayName: pulumi.Output<string | undefined>;
    /**
     * User ID of the bot account.
     */
    declare public /*out*/ readonly botUserId: pulumi.Output<string>;
    /**
     * Username of the bot to create or adopt. Defaults to "pulumi".
     */
    declare public readonly botUsername: pulumi.Output<string>;
    /**
     * System roles applied to the bot account. Defaults to ["system_user", "system_admin", "system_post_all"].
     */
    declare public readonly roles: pulumi.Output<enums.SystemRole[] | undefined>;
    /**
     * The issued access token. Use it as the token of a second provider instance.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * Description of the bot access token. Changing it rotates the token. Defaults to "pulumi".
     */
    declare public readonly tokenDescription: pulumi.Output<string>;
    /**
     * ID of the issued access token.
     */
    declare public /*out*/ readonly tokenId: pulumi.Output<string>;

    /**
     * Create a Bootstrap resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BootstrapArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.adminEmail === undefined && !opts.urn) {
                throw new Error("Missing required property 'adminEmail'");
            }
            if (args?.adminUsername === undefined && !opts.urn) {
                throw new Error("Missing required property 'adminUsername'");
            }
            resourceInputs["adminEmail"] = args?.adminEmail;
            resourceInputs["adminPassword"] = args?.adminPassword ? pulumi.secret(args.adminPassword) : undefined;
            resourceInputs["adminToken"] = args?.adminToken ? pulumi.secret(args.adminToken) : undefined;
            resourceInputs["adminUsername"] = args?.adminUsername;
            resourceInputs["baseUrl"] = args?.baseUrl;
            resourceInputs["botDescription"] = args?.botDescription;
            resourceInputs["botDisplayName"] = args?.botDisplayName;
            resourceInputs["botUsername"] = (args?.botUsername) ?? "pulumi";
            resourceInputs["roles"] = args?.roles;
            resourceInputs["tokenDescription"] = (args?.tokenDescription) ?? "pulumi";
            resourceInputs["adminUserId"] = undefined /*out*/;
            resourceInputs["botUserId"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["tokenId"] = undefined /*out*/;
        } else {
            resourceInputs["adminEmail"] = undefined /*out*/;
            resourceInputs["adminPassword"] = undefined /*out*/;
            resourceInputs["adminToken"] = undefined /*out*/;
            resourceInputs["adminUserId"] = undefined /*out*/;
            resourceInputs["adminUsername"] = undefined /*out*/;
            resourceInputs["baseUrl"] = undefined /*out*/;
            resourceInputs["botDescription"] = undefined /*out*/;
            resourceInputs["botDisplayName"] = undefined /*out*/;
            resourceInputs["botUserId"] = undefined /*out*/;
            resourceInputs["botUsername"] = undefined /*out*/;
            resourceInputs["roles"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["tokenDescription"] = undefined /*out*/;
            resourceInputs["tokenId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["adminPassword", "adminToken", "token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["botUsername"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Bootstrap.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Bootstrap resource.
 */
export interface BootstrapArgs {
    /**
     * Email of the bootstrap admin. Only used when the account is created.
     */
    adminEmail: pulumi.Input<string>;
    /**
     * Password of the bootstrap admin. Required unless adminToken is set.
     */
    adminPassword?: pulumi.Input<string | undefined>;
    /**
     * Existing system-admin token (personal access or bot token) used instead of a password login.
     */
    adminToken?: pulumi.Input<string | undefined>;
    /**
     * Username of the bootstrap admin. Created on a fresh server, used for login otherwise.
     */
    adminUsername: pulumi.Input<string>;
    /**
     * Base URL of the Mattermost instance. Defaults to the provider's base URL.
     */
    baseUrl?: pulumi.Input<string | undefined>;
    /**
     * Description of the bot.
     */
    botDescription?: pulumi.Input<string | undefined>;
    /**
     * Display name of the bot.
     */
    botDisplayName?: pulumi.Input<string | undefined>;
    /**
     * Username of the bot to create or adopt. Defaults to "pulumi".
     */
    botUsername?: pulumi.Input<string | undefined>;
    /**
     * System roles applied to the bot account. Defaults to ["system_user", "system_admin", "system_post_all"].
     */
    roles?: pulumi.Input<pulumi.Input<enums.SystemRole>[] | undefined>;
    /**
     * Description of the bot access token. Changing it rotates the token. Defaults to "pulumi".
     */
    tokenDescription?: pulumi.Input<string | undefined>;
}
