// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * Obtains a personal access token of a system-admin user without user interaction, for use as the token of a second provider instance. On a fresh server the user is signed up as the first account (which Mattermost promotes to system admin). On a running server the user is logged in with its password, or created or adopted through adminToken. Personal access tokens are enabled on the server when they are not. A refresh that finds the token rejected while the user still logs in with its password (for example after a server reset disabled personal access tokens, or after the token was revoked) marks the resource for repair, and the next update enables personal access tokens again and reissues the token when it is gone. The resource authenticates on its own, so its provider does not need a token. The resource ID is the user ID.
 */
export class Bootstrap extends pulumi.CustomResource {
    /**
     * Get an existing Bootstrap resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Bootstrap {
        return new Bootstrap(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:Bootstrap';

    /**
     * Returns true if the given object is an instance of Bootstrap.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bootstrap {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bootstrap.__pulumiType;
    }

    /**
     * Token of an existing system admin (personal access or bot token), needed only to create or adopt the user on a server that already has accounts and to recover when the issued token was revoked.
     */
    declare public readonly adminToken: pulumi.Output<string | undefined>;
    /**
     * Base URL of the Mattermost instance. Defaults to the provider's base URL.
     */
    declare public readonly baseUrl: pulumi.Output<string | undefined>;
    /**
     * Email of the admin user.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * The generated password when none was configured.
     */
    declare public /*out*/ readonly generatedPassword: pulumi.Output<string | undefined>;
    /**
     * Password of the admin user. Generated and kept in state when unset. Adopting an existing user through adminToken sets it.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * True after a refresh found the token rejected while the user could still be reached with its password or adminToken. The next update repairs the token.
     */
    declare public /*out*/ readonly repairRequired: pulumi.Output<boolean | undefined>;
    /**
     * System roles of the user. Defaults to ["system_user", "system_admin"].
     */
    declare public readonly roles: pulumi.Output<enums.SystemRole[] | undefined>;
    /**
     * The issued personal access token. Use it as the token of a second provider instance.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * Description of the personal access token. Changing it rotates the token. Defaults to "pulumi".
     */
    declare public readonly tokenDescription: pulumi.Output<string>;
    /**
     * ID of the issued personal access token.
     */
    declare public /*out*/ readonly tokenId: pulumi.Output<string>;
    /**
     * ID of the admin user.
     */
    declare public /*out*/ readonly userId: pulumi.Output<string>;
    /**
     * Username of the admin user to sign up, create, or adopt. Changing it replaces the resource.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a Bootstrap resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BootstrapArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["adminToken"] = args?.adminToken ? pulumi.secret(args.adminToken) : undefined;
            resourceInputs["baseUrl"] = args?.baseUrl;
            resourceInputs["email"] = args?.email;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["roles"] = args?.roles;
            resourceInputs["tokenDescription"] = (args?.tokenDescription) ?? "pulumi";
            resourceInputs["username"] = args?.username;
            resourceInputs["generatedPassword"] = undefined /*out*/;
            resourceInputs["repairRequired"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["tokenId"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        } else {
            resourceInputs["adminToken"] = undefined /*out*/;
            resourceInputs["baseUrl"] = undefined /*out*/;
            resourceInputs["email"] = undefined /*out*/;
            resourceInputs["generatedPassword"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["repairRequired"] = undefined /*out*/;
            resourceInputs["roles"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["tokenDescription"] = undefined /*out*/;
            resourceInputs["tokenId"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["adminToken", "generatedPassword", "password", "token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["username"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Bootstrap.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Bootstrap resource.
 */
export interface BootstrapArgs {
    /**
     * Token of an existing system admin (personal access or bot token), needed only to create or adopt the user on a server that already has accounts and to recover when the issued token was revoked.
     */
    adminToken?: pulumi.Input<string | undefined>;
    /**
     * Base URL of the Mattermost instance. Defaults to the provider's base URL.
     */
    baseUrl?: pulumi.Input<string | undefined>;
    /**
     * Email of the admin user.
     */
    email: pulumi.Input<string>;
    /**
     * Password of the admin user. Generated and kept in state when unset. Adopting an existing user through adminToken sets it.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * System roles of the user. Defaults to ["system_user", "system_admin"].
     */
    roles?: pulumi.Input<pulumi.Input<enums.SystemRole>[] | undefined>;
    /**
     * Description of the personal access token. Changing it rotates the token. Defaults to "pulumi".
     */
    tokenDescription?: pulumi.Input<string | undefined>;
    /**
     * Username of the admin user to sign up, create, or adopt. Changing it replaces the resource.
     */
    username: pulumi.Input<string>;
}
