// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Membership of a Mattermost user in a channel.
 */
export class ChannelMember extends pulumi.CustomResource {
    /**
     * Get an existing ChannelMember resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ChannelMember {
        return new ChannelMember(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:ChannelMember';

    /**
     * Returns true if the given object is an instance of ChannelMember.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ChannelMember {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ChannelMember.__pulumiType;
    }

    declare public readonly channelId: pulumi.Output<string>;
    /**
     * Grant the channel admin role to the member.
     */
    declare public readonly schemeAdmin: pulumi.Output<boolean | undefined>;
    declare public readonly userId: pulumi.Output<string>;

    /**
     * Create a ChannelMember resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ChannelMemberArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.channelId === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelId'");
            }
            if (args?.userId === undefined && !opts.urn) {
                throw new Error("Missing required property 'userId'");
            }
            resourceInputs["channelId"] = args?.channelId;
            resourceInputs["schemeAdmin"] = args?.schemeAdmin;
            resourceInputs["userId"] = args?.userId;
        } else {
            resourceInputs["channelId"] = undefined /*out*/;
            resourceInputs["schemeAdmin"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["channelId", "userId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(ChannelMember.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ChannelMember resource.
 */
export interface ChannelMemberArgs {
    channelId: pulumi.Input<string>;
    /**
     * Grant the channel admin role to the member.
     */
    schemeAdmin?: pulumi.Input<boolean | undefined>;
    userId: pulumi.Input<string>;
}
