// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A custom slash command of a team. Mattermost sends the command's token with every request to the URL, so the endpoint can verify the caller; the token is kept in state as a secret. The provider's account needs manage_slash_commands on the team. The resource ID is the command ID.
 */
export class Command extends pulumi.CustomResource {
    /**
     * Get an existing Command resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Command {
        return new Command(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:Command';

    /**
     * Returns true if the given object is an instance of Command.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Command {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Command.__pulumiType;
    }

    /**
     * Whether the command appears in the autocomplete list while typing a slash.
     */
    declare public readonly autoComplete: pulumi.Output<boolean | undefined>;
    /**
     * Short description shown in the autocomplete list.
     */
    declare public readonly autoCompleteDesc: pulumi.Output<string | undefined>;
    /**
     * Argument hint shown in the autocomplete list, e.g. `[text]`.
     */
    declare public readonly autoCompleteHint: pulumi.Output<string | undefined>;
    /**
     * ID of the user who created the command.
     */
    declare public /*out*/ readonly creatorId: pulumi.Output<string>;
    /**
     * Description shown in the integrations list (at most 128 characters).
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Name shown in the integrations list (at most 64 characters).
     */
    declare public readonly displayName: pulumi.Output<string | undefined>;
    /**
     * Profile picture the command's responses are posted with.
     */
    declare public readonly iconUrl: pulumi.Output<string | undefined>;
    /**
     * How Mattermost calls the URL: `P` for POST (form-encoded body) or `G` for GET (query string). Defaults to `P`.
     */
    declare public readonly method: pulumi.Output<string>;
    /**
     * ID of the team the command belongs to.
     */
    declare public readonly teamId: pulumi.Output<string>;
    /**
     * The token Mattermost sends with every request to the URL.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * The word after the slash that invokes the command, without the slash. Mattermost stores it in lower case.
     */
    declare public readonly trigger: pulumi.Output<string>;
    /**
     * The HTTP or HTTPS URL Mattermost calls when the command is executed.
     */
    declare public readonly url: pulumi.Output<string>;
    /**
     * Username the command's responses are posted as; the caller's username when unset.
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a Command resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CommandArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.teamId === undefined && !opts.urn) {
                throw new Error("Missing required property 'teamId'");
            }
            if (args?.trigger === undefined && !opts.urn) {
                throw new Error("Missing required property 'trigger'");
            }
            if (args?.url === undefined && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["autoComplete"] = args?.autoComplete;
            resourceInputs["autoCompleteDesc"] = args?.autoCompleteDesc;
            resourceInputs["autoCompleteHint"] = args?.autoCompleteHint;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["iconUrl"] = args?.iconUrl;
            resourceInputs["method"] = (args?.method) ?? "P";
            resourceInputs["teamId"] = args?.teamId;
            resourceInputs["trigger"] = args?.trigger;
            resourceInputs["url"] = args?.url;
            resourceInputs["username"] = args?.username;
            resourceInputs["creatorId"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        } else {
            resourceInputs["autoComplete"] = undefined /*out*/;
            resourceInputs["autoCompleteDesc"] = undefined /*out*/;
            resourceInputs["autoCompleteHint"] = undefined /*out*/;
            resourceInputs["creatorId"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["displayName"] = undefined /*out*/;
            resourceInputs["iconUrl"] = undefined /*out*/;
            resourceInputs["method"] = undefined /*out*/;
            resourceInputs["teamId"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["trigger"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Command.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Command resource.
 */
export interface CommandArgs {
    /**
     * Whether the command appears in the autocomplete list while typing a slash.
     */
    autoComplete?: pulumi.Input<boolean | undefined>;
    /**
     * Short description shown in the autocomplete list.
     */
    autoCompleteDesc?: pulumi.Input<string | undefined>;
    /**
     * Argument hint shown in the autocomplete list, e.g. `[text]`.
     */
    autoCompleteHint?: pulumi.Input<string | undefined>;
    /**
     * Description shown in the integrations list (at most 128 characters).
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Name shown in the integrations list (at most 64 characters).
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Profile picture the command's responses are posted with.
     */
    iconUrl?: pulumi.Input<string | undefined>;
    /**
     * How Mattermost calls the URL: `P` for POST (form-encoded body) or `G` for GET (query string). Defaults to `P`.
     */
    method?: pulumi.Input<string | undefined>;
    /**
     * ID of the team the command belongs to.
     */
    teamId: pulumi.Input<string>;
    /**
     * The word after the slash that invokes the command, without the slash. Mattermost stores it in lower case.
     */
    trigger: pulumi.Input<string>;
    /**
     * The HTTP or HTTPS URL Mattermost calls when the command is executed.
     */
    url: pulumi.Input<string>;
    /**
     * Username the command's responses are posted as; the caller's username when unset.
     */
    username?: pulumi.Input<string | undefined>;
}
