// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Mattermost incoming webhook bound to a channel.
 */
export class IncomingWebhook extends pulumi.CustomResource {
    /**
     * Get an existing IncomingWebhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): IncomingWebhook {
        return new IncomingWebhook(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:IncomingWebhook';

    /**
     * Returns true if the given object is an instance of IncomingWebhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IncomingWebhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IncomingWebhook.__pulumiType;
    }

    declare public readonly channelId: pulumi.Output<string>;
    declare public readonly channelLocked: pulumi.Output<boolean | undefined>;
    declare public readonly description: pulumi.Output<string | undefined>;
    declare public readonly displayName: pulumi.Output<string>;
    declare public readonly iconUrl: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly teamId: pulumi.Output<string>;
    declare public /*out*/ readonly userId: pulumi.Output<string>;
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a IncomingWebhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IncomingWebhookArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.channelId === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelId'");
            }
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            resourceInputs["channelId"] = args?.channelId;
            resourceInputs["channelLocked"] = args?.channelLocked;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["iconUrl"] = args?.iconUrl;
            resourceInputs["username"] = args?.username;
            resourceInputs["teamId"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        } else {
            resourceInputs["channelId"] = undefined /*out*/;
            resourceInputs["channelLocked"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["displayName"] = undefined /*out*/;
            resourceInputs["iconUrl"] = undefined /*out*/;
            resourceInputs["teamId"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IncomingWebhook.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a IncomingWebhook resource.
 */
export interface IncomingWebhookArgs {
    channelId: pulumi.Input<string>;
    channelLocked?: pulumi.Input<boolean | undefined>;
    description?: pulumi.Input<string | undefined>;
    displayName: pulumi.Input<string>;
    iconUrl?: pulumi.Input<string | undefined>;
    username?: pulumi.Input<string | undefined>;
}
