// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AccessTokenArgs } from "./accessToken";
export type AccessToken = import("./accessToken").AccessToken;
export const AccessToken: typeof import("./accessToken").AccessToken = null as any;
utilities.lazyLoad(exports, ["AccessToken"], () => require("./accessToken"));

export { AgentArgs } from "./agent";
export type Agent = import("./agent").Agent;
export const Agent: typeof import("./agent").Agent = null as any;
utilities.lazyLoad(exports, ["Agent"], () => require("./agent"));

export { AgentsConfigArgs } from "./agentsConfig";
export type AgentsConfig = import("./agentsConfig").AgentsConfig;
export const AgentsConfig: typeof import("./agentsConfig").AgentsConfig = null as any;
utilities.lazyLoad(exports, ["AgentsConfig"], () => require("./agentsConfig"));

export { BootstrapArgs } from "./bootstrap";
export type Bootstrap = import("./bootstrap").Bootstrap;
export const Bootstrap: typeof import("./bootstrap").Bootstrap = null as any;
utilities.lazyLoad(exports, ["Bootstrap"], () => require("./bootstrap"));

export { BotArgs } from "./bot";
export type Bot = import("./bot").Bot;
export const Bot: typeof import("./bot").Bot = null as any;
utilities.lazyLoad(exports, ["Bot"], () => require("./bot"));

export { ChannelArgs } from "./channel";
export type Channel = import("./channel").Channel;
export const Channel: typeof import("./channel").Channel = null as any;
utilities.lazyLoad(exports, ["Channel"], () => require("./channel"));

export { ChannelMemberArgs } from "./channelMember";
export type ChannelMember = import("./channelMember").ChannelMember;
export const ChannelMember: typeof import("./channelMember").ChannelMember = null as any;
utilities.lazyLoad(exports, ["ChannelMember"], () => require("./channelMember"));

export { CommandArgs } from "./command";
export type Command = import("./command").Command;
export const Command: typeof import("./command").Command = null as any;
utilities.lazyLoad(exports, ["Command"], () => require("./command"));

export { IncomingWebhookArgs } from "./incomingWebhook";
export type IncomingWebhook = import("./incomingWebhook").IncomingWebhook;
export const IncomingWebhook: typeof import("./incomingWebhook").IncomingWebhook = null as any;
utilities.lazyLoad(exports, ["IncomingWebhook"], () => require("./incomingWebhook"));

export { OAuthAppArgs } from "./oauthApp";
export type OAuthApp = import("./oauthApp").OAuthApp;
export const OAuthApp: typeof import("./oauthApp").OAuthApp = null as any;
utilities.lazyLoad(exports, ["OAuthApp"], () => require("./oauthApp"));

export { OutgoingWebhookArgs } from "./outgoingWebhook";
export type OutgoingWebhook = import("./outgoingWebhook").OutgoingWebhook;
export const OutgoingWebhook: typeof import("./outgoingWebhook").OutgoingWebhook = null as any;
utilities.lazyLoad(exports, ["OutgoingWebhook"], () => require("./outgoingWebhook"));

export { PluginArgs } from "./plugin";
export type Plugin = import("./plugin").Plugin;
export const Plugin: typeof import("./plugin").Plugin = null as any;
utilities.lazyLoad(exports, ["Plugin"], () => require("./plugin"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { SystemConfigArgs } from "./systemConfig";
export type SystemConfig = import("./systemConfig").SystemConfig;
export const SystemConfig: typeof import("./systemConfig").SystemConfig = null as any;
utilities.lazyLoad(exports, ["SystemConfig"], () => require("./systemConfig"));

export { TeamArgs } from "./team";
export type Team = import("./team").Team;
export const Team: typeof import("./team").Team = null as any;
utilities.lazyLoad(exports, ["Team"], () => require("./team"));

export { TeamMemberArgs } from "./teamMember";
export type TeamMember = import("./teamMember").TeamMember;
export const TeamMember: typeof import("./teamMember").TeamMember = null as any;
utilities.lazyLoad(exports, ["TeamMember"], () => require("./teamMember"));

export { UserArgs } from "./user";
export type User = import("./user").User;
export const User: typeof import("./user").User = null as any;
utilities.lazyLoad(exports, ["User"], () => require("./user"));


// Export enums:
export * from "./types/enums";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "mattermost:index:AccessToken":
                return new AccessToken(name, <any>undefined, { urn })
            case "mattermost:index:Agent":
                return new Agent(name, <any>undefined, { urn })
            case "mattermost:index:AgentsConfig":
                return new AgentsConfig(name, <any>undefined, { urn })
            case "mattermost:index:Bootstrap":
                return new Bootstrap(name, <any>undefined, { urn })
            case "mattermost:index:Bot":
                return new Bot(name, <any>undefined, { urn })
            case "mattermost:index:Channel":
                return new Channel(name, <any>undefined, { urn })
            case "mattermost:index:ChannelMember":
                return new ChannelMember(name, <any>undefined, { urn })
            case "mattermost:index:Command":
                return new Command(name, <any>undefined, { urn })
            case "mattermost:index:IncomingWebhook":
                return new IncomingWebhook(name, <any>undefined, { urn })
            case "mattermost:index:OAuthApp":
                return new OAuthApp(name, <any>undefined, { urn })
            case "mattermost:index:OutgoingWebhook":
                return new OutgoingWebhook(name, <any>undefined, { urn })
            case "mattermost:index:Plugin":
                return new Plugin(name, <any>undefined, { urn })
            case "mattermost:index:SystemConfig":
                return new SystemConfig(name, <any>undefined, { urn })
            case "mattermost:index:Team":
                return new Team(name, <any>undefined, { urn })
            case "mattermost:index:TeamMember":
                return new TeamMember(name, <any>undefined, { urn })
            case "mattermost:index:User":
                return new User(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("mattermost", "index", _module)
pulumi.runtime.registerResourcePackage("mattermost", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:mattermost") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
