// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Mattermost OAuth 2.0 client application.
 */
export class OAuthApp extends pulumi.CustomResource {
    /**
     * Get an existing OAuthApp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): OAuthApp {
        return new OAuthApp(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:OAuthApp';

    /**
     * Returns true if the given object is an instance of OAuthApp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OAuthApp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OAuthApp.__pulumiType;
    }

    declare public readonly callbackUrls: pulumi.Output<string[]>;
    declare public /*out*/ readonly clientSecret: pulumi.Output<string>;
    declare public /*out*/ readonly creatorId: pulumi.Output<string>;
    declare public readonly description: pulumi.Output<string | undefined>;
    declare public readonly homepage: pulumi.Output<string | undefined>;
    declare public readonly iconUrl: pulumi.Output<string | undefined>;
    declare public readonly isTrusted: pulumi.Output<boolean | undefined>;
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a OAuthApp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OAuthAppArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.callbackUrls === undefined && !opts.urn) {
                throw new Error("Missing required property 'callbackUrls'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["callbackUrls"] = args?.callbackUrls;
            resourceInputs["description"] = args?.description;
            resourceInputs["homepage"] = args?.homepage;
            resourceInputs["iconUrl"] = args?.iconUrl;
            resourceInputs["isTrusted"] = args?.isTrusted;
            resourceInputs["name"] = args?.name;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["creatorId"] = undefined /*out*/;
        } else {
            resourceInputs["callbackUrls"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["creatorId"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["homepage"] = undefined /*out*/;
            resourceInputs["iconUrl"] = undefined /*out*/;
            resourceInputs["isTrusted"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(OAuthApp.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a OAuthApp resource.
 */
export interface OAuthAppArgs {
    callbackUrls: pulumi.Input<pulumi.Input<string>[]>;
    description?: pulumi.Input<string | undefined>;
    homepage?: pulumi.Input<string | undefined>;
    iconUrl?: pulumi.Input<string | undefined>;
    isTrusted?: pulumi.Input<boolean | undefined>;
    name: pulumi.Input<string>;
}
