// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Mattermost outgoing webhook.
 */
export class OutgoingWebhook extends pulumi.CustomResource {
    /**
     * Get an existing OutgoingWebhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): OutgoingWebhook {
        return new OutgoingWebhook(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:OutgoingWebhook';

    /**
     * Returns true if the given object is an instance of OutgoingWebhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OutgoingWebhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OutgoingWebhook.__pulumiType;
    }

    declare public readonly callbackUrls: pulumi.Output<string[]>;
    declare public readonly channelId: pulumi.Output<string | undefined>;
    declare public readonly contentType: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly creatorId: pulumi.Output<string>;
    declare public readonly description: pulumi.Output<string | undefined>;
    declare public readonly displayName: pulumi.Output<string>;
    declare public readonly iconUrl: pulumi.Output<string | undefined>;
    declare public readonly teamId: pulumi.Output<string>;
    declare public /*out*/ readonly token: pulumi.Output<string>;
    declare public readonly triggerWhen: pulumi.Output<number | undefined>;
    declare public readonly triggerWords: pulumi.Output<string[] | undefined>;
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a OutgoingWebhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OutgoingWebhookArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.callbackUrls === undefined && !opts.urn) {
                throw new Error("Missing required property 'callbackUrls'");
            }
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.teamId === undefined && !opts.urn) {
                throw new Error("Missing required property 'teamId'");
            }
            resourceInputs["callbackUrls"] = args?.callbackUrls;
            resourceInputs["channelId"] = args?.channelId;
            resourceInputs["contentType"] = args?.contentType;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["iconUrl"] = args?.iconUrl;
            resourceInputs["teamId"] = args?.teamId;
            resourceInputs["triggerWhen"] = args?.triggerWhen;
            resourceInputs["triggerWords"] = args?.triggerWords;
            resourceInputs["username"] = args?.username;
            resourceInputs["creatorId"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        } else {
            resourceInputs["callbackUrls"] = undefined /*out*/;
            resourceInputs["channelId"] = undefined /*out*/;
            resourceInputs["contentType"] = undefined /*out*/;
            resourceInputs["creatorId"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["displayName"] = undefined /*out*/;
            resourceInputs["iconUrl"] = undefined /*out*/;
            resourceInputs["teamId"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["triggerWhen"] = undefined /*out*/;
            resourceInputs["triggerWords"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(OutgoingWebhook.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a OutgoingWebhook resource.
 */
export interface OutgoingWebhookArgs {
    callbackUrls: pulumi.Input<pulumi.Input<string>[]>;
    channelId?: pulumi.Input<string | undefined>;
    contentType?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    displayName: pulumi.Input<string>;
    iconUrl?: pulumi.Input<string | undefined>;
    teamId: pulumi.Input<string>;
    triggerWhen?: pulumi.Input<number | undefined>;
    triggerWords?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    username?: pulumi.Input<string | undefined>;
}
