// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Mattermost plugin. Without `downloadUrl` the plugin is installed from the marketplace, which also lists the plugins prepackaged with the server; a remote marketplace install needs PluginSettings.EnableMarketplace and EnableRemoteMarketplace. With `downloadUrl` the plugin bundle is downloaded by the server, which needs PluginSettings.EnableUploads (and AllowInsecureDownloadURL for plain HTTP). The provider's account needs manage_system. Deleting the resource removes the plugin; its settings stay in the server configuration, as they do when a plugin is removed in the System Console. The resource ID is the plugin ID.
 */
export class Plugin extends pulumi.CustomResource {
    /**
     * Get an existing Plugin resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Plugin {
        return new Plugin(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:Plugin';

    /**
     * Returns true if the given object is an instance of Plugin.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Plugin {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Plugin.__pulumiType;
    }

    /**
     * URL of the plugin bundle (a `.tar.gz`) the server downloads instead of using the marketplace. Changing it reinstalls the plugin.
     */
    declare public readonly downloadUrl: pulumi.Output<string | undefined>;
    /**
     * Whether the plugin is enabled. Defaults to true.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Version of the plugin installed on the server.
     */
    declare public /*out*/ readonly installedVersion: pulumi.Output<string>;
    /**
     * Name of the plugin from its manifest.
     */
    declare public /*out*/ readonly name: pulumi.Output<string>;
    /**
     * ID of the plugin as declared in its manifest, e.g. `mattermost-ai`.
     */
    declare public readonly pluginId: pulumi.Output<string>;
    /**
     * The plugin's settings, stored under PluginSettings.Plugins.<pluginId> in the server configuration and replacing what is there. Keys are the setting keys of the plugin's manifest. Left unmanaged when unset. Secret settings are kept from the inputs on refresh because the API masks them.
     */
    declare public readonly settings: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * Version to install from the marketplace. The latest version offered for the server is installed when unset. Changing it reinstalls the plugin. Ignored when `downloadUrl` is set.
     */
    declare public readonly version: pulumi.Output<string | undefined>;

    /**
     * Create a Plugin resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PluginArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.pluginId === undefined && !opts.urn) {
                throw new Error("Missing required property 'pluginId'");
            }
            resourceInputs["downloadUrl"] = args?.downloadUrl;
            resourceInputs["enabled"] = (args?.enabled) ?? true;
            resourceInputs["pluginId"] = args?.pluginId;
            resourceInputs["settings"] = args?.settings;
            resourceInputs["version"] = args?.version;
            resourceInputs["installedVersion"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
        } else {
            resourceInputs["downloadUrl"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["installedVersion"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["pluginId"] = undefined /*out*/;
            resourceInputs["settings"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["pluginId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Plugin.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Plugin resource.
 */
export interface PluginArgs {
    /**
     * URL of the plugin bundle (a `.tar.gz`) the server downloads instead of using the marketplace. Changing it reinstalls the plugin.
     */
    downloadUrl?: pulumi.Input<string | undefined>;
    /**
     * Whether the plugin is enabled. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * ID of the plugin as declared in its manifest, e.g. `mattermost-ai`.
     */
    pluginId: pulumi.Input<string>;
    /**
     * The plugin's settings, stored under PluginSettings.Plugins.<pluginId> in the server configuration and replacing what is there. Keys are the setting keys of the plugin's manifest. Left unmanaged when unset. Secret settings are kept from the inputs on refresh because the API masks them.
     */
    settings?: pulumi.Input<{[key: string]: any} | undefined>;
    /**
     * Version to install from the marketplace. The latest version offered for the server is installed when unset. Changing it reinstalls the plugin. Ignored when `downloadUrl` is set.
     */
    version?: pulumi.Input<string | undefined>;
}
