// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage resources on a Mattermost instance through the Mattermost API v4.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'mattermost';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Base URL of the Mattermost instance, e.g. https://mattermost.example.com. Defaults to MATTERMOST_BASE_URL.
     */
    declare public readonly baseUrl: pulumi.Output<string>;
    /**
     * Mattermost personal access token or bot token. Defaults to MATTERMOST_TOKEN.
     */
    declare public readonly token: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["baseUrl"] = (args?.baseUrl) ?? (utilities.getEnv("MATTERMOST_BASE_URL") || "");
            resourceInputs["token"] = (args?.token ? pulumi.secret(args.token) : undefined) ?? (utilities.getEnv("MATTERMOST_TOKEN") || "");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Base URL of the Mattermost instance, e.g. https://mattermost.example.com. Defaults to MATTERMOST_BASE_URL.
     */
    baseUrl?: pulumi.Input<string | undefined>;
    /**
     * Mattermost personal access token or bot token. Defaults to MATTERMOST_TOKEN.
     */
    token?: pulumi.Input<string | undefined>;
}
