// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Selected Mattermost system configuration settings. This is a singleton resource with ID 'system'. Unset fields are left unmanaged.
 */
export class SystemConfig extends pulumi.CustomResource {
    /**
     * Get an existing SystemConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): SystemConfig {
        return new SystemConfig(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mattermost:index:SystemConfig';

    /**
     * Returns true if the given object is an instance of SystemConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SystemConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SystemConfig.__pulumiType;
    }

    declare public readonly allowCorsFrom: pulumi.Output<string | undefined>;
    declare public readonly corsAllowCredentials: pulumi.Output<boolean | undefined>;
    declare public readonly disableBotsWhenOwnerIsDeactivated: pulumi.Output<boolean | undefined>;
    declare public readonly enableApiChannelDeletion: pulumi.Output<boolean | undefined>;
    declare public readonly enableApiPostDeletion: pulumi.Output<boolean | undefined>;
    declare public readonly enableApiTeamDeletion: pulumi.Output<boolean | undefined>;
    declare public readonly enableApiUserDeletion: pulumi.Output<boolean | undefined>;
    declare public readonly enableBotAccountCreation: pulumi.Output<boolean | undefined>;
    declare public readonly enableCommands: pulumi.Output<boolean | undefined>;
    declare public readonly enableCustomEmoji: pulumi.Output<boolean | undefined>;
    declare public readonly enableDynamicClientRegistration: pulumi.Output<boolean | undefined>;
    declare public readonly enableEmailInvitations: pulumi.Output<boolean | undefined>;
    declare public readonly enableEmojiPicker: pulumi.Output<boolean | undefined>;
    declare public readonly enableIncomingWebhooks: pulumi.Output<boolean | undefined>;
    declare public readonly enableMultifactorAuthentication: pulumi.Output<boolean | undefined>;
    declare public readonly enableOAuthServiceProvider: pulumi.Output<boolean | undefined>;
    declare public readonly enableOutgoingWebhooks: pulumi.Output<boolean | undefined>;
    declare public readonly enablePostIconOverride: pulumi.Output<boolean | undefined>;
    declare public readonly enablePostUsernameOverride: pulumi.Output<boolean | undefined>;
    declare public readonly enableUserAccessTokens: pulumi.Output<boolean | undefined>;
    declare public readonly enforceMultifactorAuthentication: pulumi.Output<boolean | undefined>;
    declare public readonly listenAddress: pulumi.Output<string | undefined>;
    declare public readonly maximumLoginAttempts: pulumi.Output<number | undefined>;
    declare public readonly maximumPersonalAccessTokenLifetimeDays: pulumi.Output<number | undefined>;
    declare public readonly outgoingIntegrationRequestsTimeout: pulumi.Output<number | undefined>;
    declare public readonly sessionIdleTimeoutInMinutes: pulumi.Output<number | undefined>;
    declare public readonly siteUrl: pulumi.Output<string | undefined>;

    /**
     * Create a SystemConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SystemConfigArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["allowCorsFrom"] = args?.allowCorsFrom;
            resourceInputs["corsAllowCredentials"] = args?.corsAllowCredentials;
            resourceInputs["disableBotsWhenOwnerIsDeactivated"] = args?.disableBotsWhenOwnerIsDeactivated;
            resourceInputs["enableApiChannelDeletion"] = args?.enableApiChannelDeletion;
            resourceInputs["enableApiPostDeletion"] = args?.enableApiPostDeletion;
            resourceInputs["enableApiTeamDeletion"] = args?.enableApiTeamDeletion;
            resourceInputs["enableApiUserDeletion"] = args?.enableApiUserDeletion;
            resourceInputs["enableBotAccountCreation"] = args?.enableBotAccountCreation;
            resourceInputs["enableCommands"] = args?.enableCommands;
            resourceInputs["enableCustomEmoji"] = args?.enableCustomEmoji;
            resourceInputs["enableDynamicClientRegistration"] = args?.enableDynamicClientRegistration;
            resourceInputs["enableEmailInvitations"] = args?.enableEmailInvitations;
            resourceInputs["enableEmojiPicker"] = args?.enableEmojiPicker;
            resourceInputs["enableIncomingWebhooks"] = args?.enableIncomingWebhooks;
            resourceInputs["enableMultifactorAuthentication"] = args?.enableMultifactorAuthentication;
            resourceInputs["enableOAuthServiceProvider"] = args?.enableOAuthServiceProvider;
            resourceInputs["enableOutgoingWebhooks"] = args?.enableOutgoingWebhooks;
            resourceInputs["enablePostIconOverride"] = args?.enablePostIconOverride;
            resourceInputs["enablePostUsernameOverride"] = args?.enablePostUsernameOverride;
            resourceInputs["enableUserAccessTokens"] = args?.enableUserAccessTokens;
            resourceInputs["enforceMultifactorAuthentication"] = args?.enforceMultifactorAuthentication;
            resourceInputs["listenAddress"] = args?.listenAddress;
            resourceInputs["maximumLoginAttempts"] = args?.maximumLoginAttempts;
            resourceInputs["maximumPersonalAccessTokenLifetimeDays"] = args?.maximumPersonalAccessTokenLifetimeDays;
            resourceInputs["outgoingIntegrationRequestsTimeout"] = args?.outgoingIntegrationRequestsTimeout;
            resourceInputs["sessionIdleTimeoutInMinutes"] = args?.sessionIdleTimeoutInMinutes;
            resourceInputs["siteUrl"] = args?.siteUrl;
        } else {
            resourceInputs["allowCorsFrom"] = undefined /*out*/;
            resourceInputs["corsAllowCredentials"] = undefined /*out*/;
            resourceInputs["disableBotsWhenOwnerIsDeactivated"] = undefined /*out*/;
            resourceInputs["enableApiChannelDeletion"] = undefined /*out*/;
            resourceInputs["enableApiPostDeletion"] = undefined /*out*/;
            resourceInputs["enableApiTeamDeletion"] = undefined /*out*/;
            resourceInputs["enableApiUserDeletion"] = undefined /*out*/;
            resourceInputs["enableBotAccountCreation"] = undefined /*out*/;
            resourceInputs["enableCommands"] = undefined /*out*/;
            resourceInputs["enableCustomEmoji"] = undefined /*out*/;
            resourceInputs["enableDynamicClientRegistration"] = undefined /*out*/;
            resourceInputs["enableEmailInvitations"] = undefined /*out*/;
            resourceInputs["enableEmojiPicker"] = undefined /*out*/;
            resourceInputs["enableIncomingWebhooks"] = undefined /*out*/;
            resourceInputs["enableMultifactorAuthentication"] = undefined /*out*/;
            resourceInputs["enableOAuthServiceProvider"] = undefined /*out*/;
            resourceInputs["enableOutgoingWebhooks"] = undefined /*out*/;
            resourceInputs["enablePostIconOverride"] = undefined /*out*/;
            resourceInputs["enablePostUsernameOverride"] = undefined /*out*/;
            resourceInputs["enableUserAccessTokens"] = undefined /*out*/;
            resourceInputs["enforceMultifactorAuthentication"] = undefined /*out*/;
            resourceInputs["listenAddress"] = undefined /*out*/;
            resourceInputs["maximumLoginAttempts"] = undefined /*out*/;
            resourceInputs["maximumPersonalAccessTokenLifetimeDays"] = undefined /*out*/;
            resourceInputs["outgoingIntegrationRequestsTimeout"] = undefined /*out*/;
            resourceInputs["sessionIdleTimeoutInMinutes"] = undefined /*out*/;
            resourceInputs["siteUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SystemConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a SystemConfig resource.
 */
export interface SystemConfigArgs {
    allowCorsFrom?: pulumi.Input<string | undefined>;
    corsAllowCredentials?: pulumi.Input<boolean | undefined>;
    disableBotsWhenOwnerIsDeactivated?: pulumi.Input<boolean | undefined>;
    enableApiChannelDeletion?: pulumi.Input<boolean | undefined>;
    enableApiPostDeletion?: pulumi.Input<boolean | undefined>;
    enableApiTeamDeletion?: pulumi.Input<boolean | undefined>;
    enableApiUserDeletion?: pulumi.Input<boolean | undefined>;
    enableBotAccountCreation?: pulumi.Input<boolean | undefined>;
    enableCommands?: pulumi.Input<boolean | undefined>;
    enableCustomEmoji?: pulumi.Input<boolean | undefined>;
    enableDynamicClientRegistration?: pulumi.Input<boolean | undefined>;
    enableEmailInvitations?: pulumi.Input<boolean | undefined>;
    enableEmojiPicker?: pulumi.Input<boolean | undefined>;
    enableIncomingWebhooks?: pulumi.Input<boolean | undefined>;
    enableMultifactorAuthentication?: pulumi.Input<boolean | undefined>;
    enableOAuthServiceProvider?: pulumi.Input<boolean | undefined>;
    enableOutgoingWebhooks?: pulumi.Input<boolean | undefined>;
    enablePostIconOverride?: pulumi.Input<boolean | undefined>;
    enablePostUsernameOverride?: pulumi.Input<boolean | undefined>;
    enableUserAccessTokens?: pulumi.Input<boolean | undefined>;
    enforceMultifactorAuthentication?: pulumi.Input<boolean | undefined>;
    listenAddress?: pulumi.Input<string | undefined>;
    maximumLoginAttempts?: pulumi.Input<number | undefined>;
    maximumPersonalAccessTokenLifetimeDays?: pulumi.Input<number | undefined>;
    outgoingIntegrationRequestsTimeout?: pulumi.Input<number | undefined>;
    sessionIdleTimeoutInMinutes?: pulumi.Input<number | undefined>;
    siteUrl?: pulumi.Input<string | undefined>;
}
